### ISSUE TITLE
Non-latin characters

### ISSUE THREAD

**Issue by kovtunos** [mjheagle8/tasknc#1]
Please fix non-latin chars display. I'm using version 0.5 compiled from git and Konsole terminal emulator. System locale is ru_RU.UTF-8.
Now it displays something like this: http://dl.dropbox.com/u/6763919/screenshot-033.jpeg

**Comment by mjheagle8** [comment]
Hi, I will look into this as soon as possible.

**Comment by mjheagle8** [comment]
hi, this should be supported now.  if you could test a recent git and tell me if/how it works for you, that would be great.

thanks,
mjheagle
