### ISSUE TITLE
filters do not work

### ISSUE THREAD

**Issue by eurochriskelly** [mjheagle8/tasknc#11]
Using tasknc version: v0.8-31-g022f918

Starting with:
./tasknc --filter project:myproject
does not filter tasks. Status line reads: 'filter=status.pending'

filtering in the task list results in the programming exiting. Message in runlog is 
"ERROR: it appears that your task list is empty. tasknc does not yet support empty task lists"
However, I do have a task list and it displays correctly.

**Comment by mjheagle8** [comment]
hi,

i just pushed a commit that should fix setting the filter on start.  i dont understand the second portion.  when i run a filter from within tasknc, it does not produce an error but successfully filters.  could you please provide the actions you did to produce this and/or send me a runlog?

thanks,
mjheagle

**Comment by eurochriskelly** [comment]
yes, that works. I see what has happened for the second part. In the old version I was able to filter by pressing, f(filter), p(project) and then typing part of the name of a project and it worked. All my projects happen to be written in upper case letters but tasknc accepted the lower case letters. Now it crashes if the project does not exist. e.g. I have a project SYSA and when I type project:sysa  tasknc crashes, when I type proj:SYS it works fine. By the way, this seems to affect the rc file because when I had a shortcut key for project:sysa tasknc would not start but after changing it to project:SYSA it works again.

**Comment by mjheagle8** [comment]
ah, okay.  i will consider adding a note in the documetnation regarding this.
thanks for the feedback!

-mjheagle
