### ISSUE TITLE
tasknc crashes if task list is empty

### ISSUE THREAD

**Issue by cody-somerville** [mjheagle8/tasknc#2]
I found tasknc currently crashes if the task list is empty with the following backtrace:

```
#0  0x00007ffff7836d05 in raise (sig=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
#1  0x00007ffff783aab6 in abort () at abort.c:92
#2  0x00007ffff787087b in __libc_message (do_abort=2, fmt=0x7ffff79590a0 "*** glibc detected *** %s: %s: 0x%s ***\n")
    at ../sysdeps/unix/sysv/linux/libc_fatal.c:189
#3  0x00007ffff787c58f in malloc_printerr (av=<value optimised out>, p=0x629c60) at malloc.c:6283
#4  _int_free (av=<value optimised out>, p=0x629c60) at malloc.c:4795
#5  0x00007ffff78803e3 in __libc_free (mem=<value optimised out>) at malloc.c:3738
#6  0x0000000000403cfa in pad_string (argstr=0x405f20 " ", length=1, lpad=0, rpad=1, align=114 'r') at tasknc.c:1221
#7  0x0000000000404298 in print_task_list (head=0x608120, projlen=1, desclen=114, datelen=10) at tasknc.c:1376
#8  0x0000000000402f85 in nc_main (head=0x608120) at tasknc.c:833
#9  0x000000000040546b in main (argc=1, argv=0x7fffffffe1f8) at tasknc.c:1888
```

Digging a little deeper into the code, I think I found two problems:

First: We see at tasknc.c: 1876 that tasknc expects get_tasks to return NULL if the task list is empty. This does not occur. 

I have taskwarrior 2.0.0 installed so it appears that tasknc will try to parse the output of 'task export.json status:pending'. The output of this command is:

```
$ task export.json status:pending
[task next export.json status:pending]
No matches.
```

However, based on my quick glance it doesn't appear get_tasks will ever return NULL if tw outputs anything at all.

Next: We see from the bt that pad_string is called from print_task_list at line 1376. 

``` C
                if (cur->project==NULL)
                        bufstr = pad_string(" ", projlen, 0, 1, 'r');
```

In pad_string, it will truncate the string if the length of the string is longer than the argument 'length' (which in this case is  suppose to be the length of the largest project name. Since there are no tasks, the largest project name length is zero but max_project_length always adds one so length here is one) minus lpad and rapd being applied.

We then have this in pad_string which will make the string zero length since length (1) - lpad (0) - rpad (1) equals zero and the length of str is 1.

``` C
        if ((int)strlen(str)>length-lpad-rpad)
        {
                str[length-lpad-rpad] = '\0';
                int i;
                for (i=1; i<=3; i++)
                        str[length-lpad-rpad-i] = '.';
        }
```

Finally, tasknc then crashes when it attempts to free str at the end of the function.

**Comment by mjheagle8** [comment]
cody,
thank you very much for your input.  i just pushed two patches that should address each of the two issues that you noted, respectively.  
i appreciate the testing, and the code analysis was very helpful.
thanks,
mjheagle
