### ISSUE TITLE
Improve handling of "started" tasks

### ISSUE THREAD

**Issue by qjcg** [mjheagle8/tasknc#3]
- add a keybinding to mark a task as "started" / "stopped"
- indicate a task's "started" / "stopped" status visually in the GUI

**Comment by mjheagle8** [comment]
hi,
this sounds like a good idea.  i am thinking maybe indicating this status as a color change.  
thanks,
mike

**Comment by qjcg** [comment]
A color change seems like it would be a good approach.

The official command line "task" client does a fairly good job in that respect---when listing current tasks, active tasks are highlighted using a bright color, and there is also an asterisk in the "active" field.

Thanks and keep up the good work on this promising tool!

**Comment by mjheagle8** [comment]
thank you!

i agree, i am hoping that taskwarrior will soon implement color fields in the json export data, so i could use the task generated colors in my ui.  i am shying away from adding an additional column at this time, but we will see about that in the future.

**Comment by mjheagle8** [comment]
color rules are implemented in the master branch at present. coloring by started/stopped is now possible.
