### ISSUE TITLE
segfault, cannot open config file

### ISSUE THREAD

**Issue by quesada** [mjheagle8/tasknc#4]
Thanks mjheagle8 for bulinding this.

It segfaults on my box, though:

$ make
gcc -Wall -g -Wextra tasknc.c -o tasknc -lncurses  
(acme)quesada@hplappy:~/coding/tasknc $ tasknc  
bash: tasknc: command not found  
(acme)quesada@hplappy:~/coding/tasknc $ ./tasknc  
task version: 2.0.0  
config file could not be opened  
Segmentation fault                           

$ cat config                                                                    
# tasknc config file

```
# by mjheagle
########

# time for ncurses cmds (getch) to expire (in ms)
# this is visible in the time that the window takes to refresh on resize
# but will consume more cpu with a lower time
nc_timeout = 500

# time for statusbar messages to expire (in s)
statusbar_timeout = 3

# default sort mode
# d: due date
# n: index
# p: project
# r: priority
sortmode = d

# boolean to determine if filters should persist until they are cleared
filter_persist = 1

# boolean to determine if filters should cascade
filter_cascade = 1
```

Any idea why?

**Comment by mjheagle8** [comment]
Hi,
my first guess would indicate that the configuration file is in the wrong location. Where is it? It must bee located as indicated in the README/man page.
Hope that helps.  Thanks,
mjheagle

**Comment by mjheagle8** [comment]
quesada,

could you check a recent git and see if this is still an issue for you?

if not, i would like to close this issue.

thanks,
mjheagle
