### ISSUE TITLE
compiling under ubuntu not working

### ISSUE THREAD

**Issue by eurochriskelly** [mjheagle8/tasknc#5]
Works if I change the order of link parameters in the Makefile. i.e. 

LDFLAGS = -lncursesw

\-  $(CC) -c $(CFLAGS) $<
+  $(CC) -c $(CFLAGS) $< $(LDFLAGS)

\-  $(CC) $(CFLAGS) -o $@ $(OBJ)
+  $(CC) $(CFLAGS) -o $@ $(OBJ) $(LDFLAGS)

**Comment by mjheagle8** [comment]
interesting. what version of gcc are you running?
