### ISSUE TITLE
cannot delete tasks anymore

### ISSUE THREAD

**Issue by eurochriskelly** [mjheagle8/tasknc#6]
tasknc version (git describe):  v0.5-380-ga713f6d

log output:

[2012-08-16 11:00:50] DEBUG: selline:4 offset:[2012-08-16 11:01:04] ERROR: SEGFAULT
[2012-08-16 11:01:04] ERROR: segmentation fault, exiting

**Comment by mjheagle8** [comment]
Chris,
It looks like something didnt get properly linked. Try this:
git pull
make clean
make

Thanks,
Mike

**Comment by eurochriskelly** [comment]
Sorry for slow response. It still doesnt work for me. Using version v0.8-17-ge541ee9. Now its behaving differently though. it hangs when I try to delete a task. I'm using task 2.1.1 whether this should make any difference.

**Comment by mjheagle8** [comment]
Chris,
Do you have no confirm set in your taskrc? At the moment that must be set
to run some of the task commands in the background.
Thanks,
Mjheagle

**Comment by eurochriskelly** [comment]
That was it! I had no confirmation line in my taskrc. I have added it now and it works!

confirmation = no

However, I am running an older version of tasknc and it does not need confirmation=no in the taskrc file!

**Comment by mjheagle8** [comment]
In older versions, my deleting code did not require this setting, that is
correct. I will be implementing a tasknc setting that allows this option to
not be set in the near future.
Thanks,
mjheagle

**Comment by eurochriskelly** [comment]
Thanks. The new version is really taking shape now :)
