### ISSUE TITLE
Tasks containing " characters are truncated

### ISSUE THREAD

**Issue by greenrd** [mjheagle8/tasknc#8]
If you create, using tasknc, a task whose description is:

```
Report "text after quotation mark goes missing" bug
```

then the description in the tasklist is truncated - it doesn't include the first " character or anything after it.

**Comment by mjheagle8** [comment]
Good catch. My json parser is currently hardcoded to assume that the field
is enclosed in double quotes. I will have to fix that.
Thanks for using tasknc!
-mjheagle

**Comment by mjheagle8** [comment]
this should be fixed with the newest commits. please tell me if it does not.

thanks for trying tasknc!
- mjheagle
