### ISSUE TITLE
Segfault if run by a different user and message logged

### ISSUE THREAD

**Issue by greenrd** [mjheagle8/tasknc#9]
When I tried to run `tasknc` as a different user, it failed, and tried to write a log message, and then segfaulted.

After I removed `/tmp/.tasknc_runlog`, it logged the error and shut down cleanly as expected.

I guess the problem is that `tasknc` can't open that file when run as the second user, because (if it still exists and hasn't been cleaned up by `tmpwatch`) it is owned by the first user.

**Comment by mjheagle8** [comment]
Aah, I did not consider this. I will patch it to append the username to the
file location as a solution to this bug.

Thanks for using tasknc!
-mjheagle

**Comment by mjheagle8** [comment]
my newest commit should fix this.  please check and tell me if it does not work.

thanks!
